ALTER TABLE url_entity ADD COLUMN processed BOOLEAN DEFAULT FALSE;
update url_entity set processed = true from tweet where tweet.id = tweet_id and tweet.processed = true;
CREATE INDEX ix_ue_processed ON url_entity USING btree (processed);
CREATE INDEX ix_ue_expanded ON url_entity USING btree (expanded);
ALTER TABLE WEB_COLLECTION ADD COLUMN TOTAL_TWEETS BIGINT DEFAULT 0;
ALTER TABLE WEB_COLLECTION ADD COLUMN TOTAL_URLS_ORIGINAL BIGINT DEFAULT 0;
ALTER TABLE WEB_COLLECTION ADD COLUMN TOTAL_URLS_EXPANDED BIGINT DEFAULT 0;
ALTER TABLE WEB_COLLECTION ADD COLUMN TOTAL_URL_ERRORS BIGINT DEFAULT 0;
ALTER TABLE WEB_COLLECTION ALTER COLUMN NAME SET NOT NULL;
ALTER TABLE URL_ENTITY ADD COLUMN creation_date date;
update url_entity set creation_date = tweet.creation_date from tweet where tweet.id = tweet_id;
update url_entity set popularity = retweet_count from tweet where retweet_count > 0 and tweet.id = tweet_id;
CREATE INDEX ix_ue_creation_date ON url_entity USING btree (creation_date);
INSERT INTO WEB_COLLECTION(ID, CREATION_DATE, DESCRIPTION, NAME, TOTAL_TWEETS, TOTAL_URLS_ORIGINAL, TOTAL_URLS_EXPANDED, TOTAL_URL_ERRORS) VALUES (1, NOW(), 'Bucket for URLs that cannot be associated with a Web Collection', 'UNKNOWN', 0, 0, 0, 0);
update tweet set processed = false from url_entity where tweet.id = tweet_id and web_collection_id is null;
